version: '3'

services:
  user_api_db:
    image: postgres
    volumes:
      - user_api_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user_api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    environment:
      - USER_API_DB_USERNAME=postgres
      - USER_API_DB_PASSWORD=
      - USER_API_DB_HOST=user_api_db
    ports:
      - "3000:3000"
    depends_on:
      - user_api_db

volumes:
  user_api_db_data: